# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Asociación de Ostomizados de Tenerife
email: info@aotentenerife.org
description: > # this means to ignore newlines until "baseurl:"
  Bienvenido a la página web de la Asociación de Ostomizados de Tenerife.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.aotentenerife.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
destination: www
exclude: [ 'CNAME', '.htaccess' ]

